packages:
  - apps/*
  - packages/*
  - scripts/*

catalog:
  '@trpc/client': ^11.1.4
  '@trpc/server': ^11.1.4
  '@trpc/tanstack-react-query': ^11.1.4
  '@types/node': ^22.15.21
  autumn-js: ^0.0.48
  better-auth: ^1.3.4
  drizzle-kit: 0.31.4
  drizzle-orm: ^0.43.1
  react: ^19.1.0
  react-dom: ^19.1.0
  superjson: ^2.2.2
  typescript: ^5.8.3
  wrangler: ^4.32.0
  zod: ^3.25.42

onlyBuiltDependencies:
  - '@sentry/cli'
  - '@tailwindcss/oxide'
  - better-sqlite3
  - core-js
  - core-js-pure
  - esbuild
  - msw
  - sharp
  - unrs-resolver
  - workerd

patchedDependencies:
  novel: patches/novel.patch
